# Generated by Django 4.1.5 on 2023-03-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commercialapi', '0003_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='heure',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
